### ISSUE TITLE
How did you get the human skeleton keypoints？

### ISSUE THREAD

**Issue by thraster** [zhumanli/SGCN4HOI#1]
Hi Manli,

Great job you are doing here! I have read your paper, but I didn't get the clue of how/where did you get the human skeleton keypoints,
can you tell me about this?

Thanks a lot!

**Comment by zhumanli** [comment]
Hi,

Thanks for your interest! 

We use the ground-truth human skeleton keypoints, since our focus is object keypoints extraction. This is written in the second paragraph of Section III.A Model Architecture, might be a bit hard to notice!

**Comment by thraster** [comment]
Hi Manli,

Thank you for your reply! By the way could you pls tell me where are those ground truth human skeleton keypoints came from? is that already in V-coco dataset?

Thanks a lot!

**Comment by zhumanli** [comment]
> 

Hi,

The human keypoints are normally not included in vcoco directly. I extracted them from coco annotations and added them to Object_Detections_vcoco which is created by VSGNet. Hope this helps. 

Please feel free to let me know if you want to discuss anything further.

**Comment by thraster** [comment]
Hi, manli

Thank you for you response, I think this will helps me a lot!
